# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments.rb

# SEO settings
title: Braulio's site
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"

# Site settings
url: 
baseurl: 
# baseurl: ""

# Author settings
author:
  name      : Braulio Vargas
  job       : Computer Engineering Student
  bio       : "Computer Engineering student of University of Granada, interested on machine learning, data science, computer vision, photography..."
  thumb     : /images/author.jpg
  email     : brauliovarlop@correo.ugr.es
  url       : brauliov.github.io
  github    : http://github.com/BraulioV
  twitter   : http://twitter.com/brau_vl
  facebook  : 
  linkedin  : http://linkedin.com/in/brauliovargaslopez

# google_analytics: UA-52446115-1
repo: 

# comments
disqus_shortname: 
